Assignment 1 : Hasan Samir Hasan - AMIT-AI Online 75

In [2]:
import numpy as np

1. Write a NumPy program to test whether none of the elements of a given array is zero.

In [14]:
v1=np.array([11,5,0,3,6,0,9,5,4,0,2,5])
v2=np.array([5,6,7,1,4,9,3,8,1,0,7,9])
print(v1!=0)
print(v2!=0)
#v1[v1!=0]


[ True  True False  True  True False  True  True  True False  True  True]
[ True  True  True  True  True  True  True  True  True False  True  True]


2. Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [15]:
print(np.any(v1==0))
print(np.any(v2==0))

True
True


3. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two
given

In [16]:
np.isclose(v1,v2,atol=1)

array([False,  True, False, False, False, False, False, False, False,
        True, False, False])

4. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.


In [22]:
zeros10=np.zeros(10)
print(zeros10)
ones10=np.ones(10)
print(ones10)
fives10=np.full(10,5)
print(fives10)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 5 5 5 5 5 5 5 5]


5. Write a NumPy program to create an array of the integers from 30 to70.


In [23]:
arr3070=np.arange(30,70)
print(arr3070)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


6. Write a NumPy program to create a 3x3 identity matrix

In [27]:
ident3x3=np.identity(3)
print(ident3x3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


7. Write a NumPy program to generate a random number between 0 and 1


In [40]:
randnum=np.random.random()
print(randnum)

0.03250201783155704


8. Write a NumPy program to generate an array of 15 random numbers from a standard normal
distribution

In [44]:
randmat=np.random.normal(5,1,size=15)
print(randmat)

[5.41470717 4.90546999 6.42089563 5.70825521 5.03557222 4.90862385
 5.38122618 5.35525386 5.14110705 4.62622045 4.90223438 4.92626202
 4.51039116 5.49252475 5.5563171 ]


9. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values
except the first and last

In [55]:
v3=np.arange(15,155)
print("v3 the original: ")
print(v3)
print("-"*100)
print("v3 except the first and last values: ")
print(v3[1:-1])


v3 the original: 
[ 15  16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32
  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86
  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104
 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122
 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140
 141 142 143 144 145 146 147 148 149 150 151 152 153 154]
----------------------------------------------------------------------------------------------------
v3 except the first and last values: 
[ 16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33
  34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51
  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69
  70  71  72  73  74  75  76  77  78  79  80  81  82  8

10. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10


In [83]:
v4=np.random.randint(0,11,(1,11))
print(v4)

[[ 2  3 10  5  7  2  4  2  6  8  3]]


11. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal
to 1, and inside 0.

In [106]:
zeros_mat10x10=np.zeros((10,10))
zeros_mat10x10[:1]=1
zeros_mat10x10[-1:]=1
zeros_mat10x10[:,:1]=1
zeros_mat10x10[:,-1:]=1
print(zeros_mat10x10)
print("-"*50)
print("Another Way: ")
ones_mat10x10=np.ones((10,10))
ones_mat10x10[1:-1,1:-1]=0
print(ones_mat10x10)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
--------------------------------------------------
Another Way: 
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2,
3, 4, 5.

In [108]:
zeros_mat5x5=np.zeros((5,5))
np.fill_diagonal(zeros_mat5x5,(1,2,3,4,5))
print(zeros_mat5x5)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


13. Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main
diagonal.

In [138]:
mat2=np.zeros((4,4))

for i in range(4):
    for j in range(4):
        if i!=j:
            mat2[i,j]=(i+j)%2

print(mat2)


[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


14 . Write a NumPy program to save two given arrays into a single file in compressed format (.npz format)
and load it

In [153]:
mat3=np.random.randint(0,100,(50,50))
mat4=np.random.randint(100,500,(100,100))
np.savez("my_data.npz",mat3=mat3,mat4=mat4)

my_loaded_data=np.load("my_data.npz")
mat3_loaded=my_loaded_data["mat3"]
mat4_loaded=my_loaded_data["mat4"]

print(mat3_loaded)
print(mat4_loaded)


[[68 70 87 ... 32 56 19]
 [69 89 24 ... 46  6 95]
 [73 73 45 ... 71 60 45]
 ...
 [23 89 58 ... 31 87 50]
 [44 38 51 ... 31 54 34]
 [46 78 89 ... 71 50 76]]
[[464 333 117 ... 190 383 426]
 [296 337 112 ... 291 189 344]
 [445 408 493 ... 248 175 221]
 ...
 [222 315 454 ... 274 245 392]
 [336 430 322 ... 246 332 207]
 [452 322 430 ... 328 398 428]]


15. Write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values.

In [162]:
np.random.seed(17)
v5=np.random.randint(0,10,size=40)
print(v5)

[1 6 6 9 0 6 4 7 4 7 1 1 9 8 2 3 6 6 9 9 1 5 1 0 5 6 6 2 6 9 8 3 2 1 9 8 3
 2 7 8]


16. Write a NumPy program to extract all numbers from a given array which are less and greater than a
specified number.

In [237]:
v6=np.array([8,24,67,87,79,49,10,94,52,98,53,66,98,14,24,15,60,58,16,9,93,86,2,2,74,31,13,83,91])

print(v6[v6>=50]) # Greater than
print(v6[v6<=30]) # Less than
print(v6[(v6<50)&(v6>20)]) # Greater and Less than

[67 87 79 94 52 98 53 66 98 60 58 93 86 74 83 91]
[ 8 24 10 14 24 15 16  9  2  2 13]
[24 49 24 31]
